const fs = require('fs');
const vm = require('vm');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8');
const sandbox = { document: {}, Tapp: { lifecycle: { onReady() {} } }, console, URL };
vm.runInNewContext(source + '\nthis.__test = { data: METRO_DATA, metroState, findRoute, validCity, extractOnlineMap, extractCityVersion, extractOfficialFare, isKnownCityId, safeCityId, safeStationSlug, safePlannerRoute, safeMetroMapUrl };', sandbox);
const { data, metroState, findRoute, validCity, extractOnlineMap, extractCityVersion, safeCityId, safeStationSlug, safePlannerRoute, safeMetroMapUrl } = sandbox.__test;
const sortedCities = sandbox.sortedCities;
const lineTagName = sandbox.lineTagName;
const lineIndexName = sandbox.lineIndexName;
const extractOfficialFare = sandbox.extractOfficialFare;
const formatRequestedTime = sandbox.formatRequestedTime;
if (!data.beijing.lines.length) throw new Error('北京线路数据不能为空');
const initialCities = sortedCities();
if (initialCities[0].id !== 'beijing') throw new Error('内置城市应优先展示');
if (initialCities[1].id !== 'shanghai' || initialCities[2].id !== 'guangzhou') throw new Error('MetroMan 官方城市顺序未保持');
if (lineIndexName({ id: '1号线' }) !== '1号线' || lineTagName({ id: '1号线' }) !== '1') throw new Error('线路索引/标签简称规则错误');
if (lineIndexName({ id: '首都机场线' }) !== '首都机场线' || lineTagName({ id: '首都机场线' }) !== '首都机场') throw new Error('特殊线路名称规则错误');
if (lineIndexName({ id: 'Line 2' }) !== 'Line 2' || lineTagName({ id: 'Line 2' }) !== '2' || lineTagName({ id: 'Airport Express Line' }) !== 'Airport Express') throw new Error('英文线路简称错误');
if (lineIndexName({ id: '首都机场线' }) !== '首都机场线') throw new Error('线路索引应显示完整名称');
if (extractOfficialFare(' <span>票价 &#165;4</span> ') !== '票价 ¥4' || extractOfficialFare('票价 ¥2') !== '票价 ¥2') throw new Error('旧版票价解析错误');
if (extractOfficialFare('票价 &#xA5;5') !== '票价 ¥5') throw new Error('HTML 实体票价解析错误');
if (formatRequestedTime('2026-08-19T21:34', 'depart') !== '2026年8月19日 周三 21:34 出发') throw new Error('用户出发时间格式错误');
data.shanghai = { name: '上海', lines: [{ id: '测试线', color: '#123456', stations: ['甲', '乙'] }] };
const cachedCities = sortedCities();
if (cachedCities.slice(0, 2).map((city) => city.id).sort().join(',') !== 'beijing,shanghai') throw new Error('缓存城市应集中排在未缓存城市前');
delete data.shanghai;
const direct = findRoute('西直门', '积水潭');
if (!direct || direct.transfers !== 0 || direct.hops !== 1) throw new Error('环线首尾连接计算错误');
const transfer = findRoute('西直门', '国贸');
if (!transfer || transfer.transfers < 1 || transfer.stations[0] !== '西直门' || transfer.stations[transfer.stations.length - 1] !== '国贸') throw new Error('换乘路线计算错误');
if (findRoute('不存在的站', '国贸') !== null) throw new Error('无效站点应返回 null');
const shanghai = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'assets', 'shanghai.json'), 'utf8'));
if (!validCity(shanghai) || shanghai.lines.length !== 28) throw new Error('上海 CSV 生成数据无效');
data.shanghai = shanghai;
metroState.city = 'shanghai';
const shanghaiRoute = findRoute('莘庄', '陆家嘴');
if (!shanghaiRoute || shanghaiRoute.transfers !== 1 || shanghaiRoute.stations.indexOf('人民广场') < 0) throw new Error('上海跨线换乘计算错误');
const cityVersion = extractCityVersion('beijing,20260710,2636291\nshanghai,20260806,3359636', 'shanghai');
if (!cityVersion || cityVersion.version !== '20260806' || cityVersion.zipBytes !== 3359636) throw new Error('MetroMan 版本清单解析错误');
if (extractOnlineMap("url: '/assets/img/metro/map/routemap_sh_cn.png'") !== 'https://www.metroman.cn/assets/img/metro/map/routemap_sh_cn.png') throw new Error('在线线路图地址解析错误');
if (safeMetroMapUrl('http://www.metroman.cn/assets/img/metro/map/routemap_sh_cn.png', false) !== '') throw new Error('线路图必须使用 HTTPS');
if (safeMetroMapUrl('https://evil.example/routemap_sh_cn.png', false) !== '') throw new Error('线路图非官方域名应被拒绝');
if (safeMetroMapUrl('https://www.metroman.cn/assets/img/metro/map/other.png', false) !== '') throw new Error('非线路图 PNG 应被拒绝');
if (extractOnlineMap("src='https://evil.example/routemap_sh_cn.png'", 'shanghai') !== null) throw new Error('恶意线路图地址不应被解析');
if (safeStationSlug('xujiahui') !== 'xujiahui' || safeStationSlug('../secret') !== '' || safeStationSlug('徐家汇') !== '') throw new Error('站点 slug 白名单校验错误');
if (safePlannerRoute('xujiahui-to-lujiazui') !== 'xujiahui-to-lujiazui' || safePlannerRoute('../secret-to-lujiazui') !== '' || safePlannerRoute('xujiahui-to-lujiazui-to-secret') !== '') throw new Error('规划路径白名单校验错误');
let invalidCityRejected = false;
try { safeCityId('../evil'); } catch (_) { invalidCityRejected = true; }
if (!invalidCityRejected) throw new Error('非法城市 ID 应被拒绝');
console.log('metro route tests passed');
