var CONFIG_KEY='cdn-cache.config.v1',LOG_KEY='cdn-cache.logs.v1',DEDUPE_KEY='cdn-cache.dedupe.v1',MAX_LOGS=80,DEDUPE_MS=5000;
var state={config:null,logs:[],busy:false,isAdmin:false};
function $(id){return document.getElementById(id)}
var toastTimer=null;
function localNotify(message,type){var toast=$('local-toast');if(!toast){toast=document.createElement('div');toast.id='local-toast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.appendChild(toast)}toast.className='local-toast '+(type||'info')+' show';toast.textContent=message;if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(function(){toast.classList.remove('show')},3200)}
async function notify(message,type){var kind=type||'info';localNotify(message,kind);try{if(Tapp.ui&&typeof Tapp.ui.showNotification==='function')await Tapp.ui.showNotification({title:kind==='success'?'成功':kind==='error'?'错误':kind==='warning'?'注意':'提示',message:message,type:kind,duration:3200})}catch(e){console.warn('[CDN Cache] notification bridge failed',e)}}
async function currentAdmin(){try{return(await Tapp.user.getRole())==='admin'&&await Tapp.user.isAdmin()}catch(e){return false}}
function showAccess(admin){$('admin-ui').hidden=!admin;$('public-ui').hidden=admin}
async function requireAdmin(){var allowed=await currentAdmin();state.isAdmin=allowed;if(!allowed){showAccess(false);notify('仅站点管理员可以管理 CDN','error')}return allowed}
function clean(value){return String(value||'').trim()}
function safeError(error){var text=error&&error.message?error.message:String(error||'请求失败');return text.replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]').replace(/(?:AKID|AKIA|LTAI)[A-Za-z0-9]+/g,'[REDACTED]')}
function normalizeConfig(value){value=value&&typeof value==='object'?value:{};var providers=['cloudflare','edgeone','aliyun'];return{provider:providers.indexOf(value.provider)>=0?value.provider:'cloudflare',zoneId:clean(value.zoneId),cfToken:clean(value.cfToken),secretId:clean(value.secretId),secretKey:clean(value.secretKey),edgeMethod:value.edgeMethod==='delete'?'delete':'invalidate',aliAccessKeyId:clean(value.aliAccessKeyId),aliAccessKeySecret:clean(value.aliAccessKeySecret),siteUrl:clean(value.siteUrl).replace(/\/+$/,'')}}
function readInputs(){return normalizeConfig({provider:$('provider').value,zoneId:$('zone-id').value,cfToken:$('cf-token').value,secretId:$('secret-id').value,secretKey:$('secret-key').value,edgeMethod:$('edge-method').value,aliAccessKeyId:$('ali-access-key-id').value,aliAccessKeySecret:$('ali-access-key-secret').value,siteUrl:$('site-url').value})}
function fillInputs(c){$('provider').value=c.provider;$('zone-id').value=c.zoneId;$('cf-token').value=c.cfToken;$('secret-id').value=c.secretId;$('secret-key').value=c.secretKey;$('edge-method').value=c.edgeMethod;$('ali-access-key-id').value=c.aliAccessKeyId;$('ali-access-key-secret').value=c.aliAccessKeySecret;$('site-url').value=c.siteUrl;renderProvider()}
function providerName(provider){return{cloudflare:'Cloudflare',edgeone:'腾讯云 EdgeOne',aliyun:'阿里云 CDN'}[provider]||provider}
function renderProvider(){var p=$('provider').value;['cloudflare','edgeone','aliyun'].forEach(function(name){$(name+'-fields').hidden=p!==name});$('resource-id-field').hidden=p==='aliyun';$('provider-badge').textContent=providerName(p)}
function parseUrls(){var seen={};return $('urls').value.split(/\r?\n|,/).map(clean).filter(function(url){if(!/^https?:\/\//i.test(url)||seen[url])return false;seen[url]=true;return true})}
function setBusy(busy){state.busy=busy;['save-btn','clear-config-btn','purge-urls-btn','purge-all-btn'].forEach(function(id){$(id).disabled=busy})}
async function saveLogs(){await Tapp.storage.set(LOG_KEY,state.logs.slice(0,MAX_LOGS))}
async function addLog(ok,title,detail){state.logs.unshift({id:Date.now()+'-'+Math.random().toString(16).slice(2),ok:ok,title:title,detail:detail,time:new Date().toISOString()});state.logs=state.logs.slice(0,MAX_LOGS);await saveLogs();renderLogs()}
function renderLogs(){var box=$('logs');box.replaceChildren();if(!state.logs.length){var empty=document.createElement('div');empty.className='empty';empty.textContent='暂无刷新记录';box.appendChild(empty);return}state.logs.forEach(function(item){var row=document.createElement('div');row.className='log'+(item.ok?'':' error');var dot=document.createElement('span');dot.className='log-status';var main=document.createElement('div');main.className='log-main';var title=document.createElement('div');title.className='log-title';title.textContent=item.title;var detail=document.createElement('div');detail.className='log-detail';detail.textContent=item.detail;var time=document.createElement('time');time.className='log-time';time.textContent=new Date(item.time).toLocaleString();main.appendChild(title);main.appendChild(detail);row.appendChild(dot);row.appendChild(main);row.appendChild(time);box.appendChild(row)})}
function validate(c){if(c.provider==='cloudflare'&&!c.zoneId)return '请填写 Zone ID';if(!c.siteUrl||!/^https:\/\//i.test(c.siteUrl))return '站点地址必须是 HTTPS URL';if(c.provider==='cloudflare'&&!c.cfToken)return '请填写 Cloudflare API Token';if(c.provider==='edgeone'&&(!c.zoneId||!c.secretId||!c.secretKey))return '请填写 EdgeOne Zone ID、SecretId 和 SecretKey';if(c.provider==='aliyun'&&(!c.aliAccessKeyId||!c.aliAccessKeySecret))return '请填写阿里云 AccessKey ID 和 AccessKey Secret';return ''}
function utf8(value){return new TextEncoder().encode(value)}
function hex(buffer){return Array.from(new Uint8Array(buffer)).map(function(v){return v.toString(16).padStart(2,'0')}).join('')}
function base64(buffer){var bytes=new Uint8Array(buffer),text='';bytes.forEach(function(v){text+=String.fromCharCode(v)});return btoa(text)}
async function sha256(value){return hex(await crypto.subtle.digest('SHA-256',utf8(value)))}
async function hmac(key,message,raw,hash){var bytes=typeof key==='string'?utf8(key):key;var cryptoKey=await crypto.subtle.importKey('raw',bytes,{name:'HMAC',hash:hash||'SHA-256'},false,['sign']);var result=await crypto.subtle.sign('HMAC',cryptoKey,utf8(message));return raw?new Uint8Array(result):hex(result)}
function edgePayload(c,urls,all){return all?{Method:c.edgeMethod,Type:'purge_all',ZoneId:c.zoneId}:{Method:c.edgeMethod,Targets:urls.map(function(value){return new URL(value).href}),Type:'purge_url',ZoneId:c.zoneId}}
async function edgeAuth(c,payload){var timestamp=Math.floor(Date.now()/1000),date=new Date(timestamp*1000).toISOString().slice(0,10),service='teo',host='teo.tencentcloudapi.com',action='createpurgetask',contentType='application/json',canonicalBody=JSON.stringify(payload),canonicalHeaders='content-type:'+contentType+'\n'+'host:'+host+'\n'+'x-tc-action:'+action+'\n',signedHeaders='content-type;host;x-tc-action',canonicalRequest='POST\n/\n\n'+canonicalHeaders+'\n'+signedHeaders+'\n'+await sha256(canonicalBody),scope=date+'/'+service+'/tc3_request',stringToSign='TC3-HMAC-SHA256\n'+timestamp+'\n'+scope+'\n'+await sha256(canonicalRequest),secretDate=await hmac('TC3'+c.secretKey,date,true),secretService=await hmac(secretDate,service,true),secretSigning=await hmac(secretService,'tc3_request',true),signature=await hmac(secretSigning,stringToSign,false);return{timestamp:String(timestamp),authorization:'TC3-HMAC-SHA256 Credential='+c.secretId+'/'+scope+', SignedHeaders='+signedHeaders+', Signature='+signature,canonicalBody:canonicalBody}}
function percent(value){return encodeURIComponent(String(value)).replace(/[!'()*]/g,function(ch){return'%'+ch.charCodeAt(0).toString(16).toUpperCase()})}
async function aliyunQuery(c,urls,all){var params={AccessKeyId:c.aliAccessKeyId,Action:'RefreshObjectCaches',Format:'JSON',ObjectPath:all?c.siteUrl+'/':urls.join('\n'),ObjectType:all?'Directory':'File',SignatureMethod:'HMAC-SHA1',SignatureNonce:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),SignatureVersion:'1.0',Timestamp:new Date().toISOString().replace(/\.\d{3}Z$/,'Z'),Version:'2018-05-10'};var canonical=Object.keys(params).sort().map(function(k){return percent(k)+'='+percent(params[k])}).join('&'),stringToSign='GET&%2F&'+percent(canonical),signatureBuffer=await hmac(c.aliAccessKeySecret+'&',stringToSign,true,'SHA-1');return canonical+'&Signature='+percent(base64(signatureBuffer))}
async function checkDedupe(key){var saved=await Tapp.storage.get(DEDUPE_KEY)||{},now=Date.now();if(saved[key]&&now-saved[key]<DEDUPE_MS)return false;saved[key]=now;Object.keys(saved).forEach(function(k){if(now-saved[k]>60000)delete saved[k]});await Tapp.storage.set(DEDUPE_KEY,saved);return true}
async function callPurge(urls,all){if(!(await requireAdmin()))return;var c=readInputs(),error=validate(c);if(error)return notify(error,'warning');var label=all?'全站缓存':urls.length+' 个 URL';if(!all&&!urls.length)return notify('请输入至少一个有效的 HTTP(S) URL','warning');var dedupeId=c.provider+'|'+(all?'all':urls.slice().sort().join('|'));if(!(await checkDedupe(dedupeId)))return notify('相同刷新请求 5 秒内不会重复提交','warning');setBusy(true);$('last-result').textContent='正在提交…';try{var result;if(c.provider==='cloudflare'){result=all?await Tapp.api('cloudflarePurgeAll',{zoneId:c.zoneId,token:c.cfToken}):await Tapp.api('cloudflarePurgeUrls',{zoneId:c.zoneId,token:c.cfToken,files:urls});if(result&&result.success===false)throw new Error((result.errors&&result.errors[0]&&result.errors[0].message)||'Cloudflare 返回失败')}else if(c.provider==='edgeone'){var edgeBody=edgePayload(c,urls,all),edgeSignature=await edgeAuth(c,edgeBody),edgeParams={payload:edgeBody,timestamp:edgeSignature.timestamp,authorization:edgeSignature.authorization};result=all?await Tapp.api('edgeOnePurgeAll',edgeParams):await Tapp.api('edgeOnePurgeUrls',edgeParams);if(result&&result.Response&&result.Response.Error)throw new Error(result.Response.Error.Code+': '+result.Response.Error.Message)}else if(c.provider==='aliyun'){var query=await aliyunQuery(c,urls,all);result=await Tapp.api('aliyunPurge',{query:query});if(result&&result.Code)throw new Error(result.Code+': '+(result.Message||'阿里云返回失败'))}else throw new Error('不支持的 CDN 服务商');$('last-result').textContent='提交成功';await addLog(true,providerName(c.provider)+' · '+label,all?'已提交全站缓存清理':urls.join(' · '));await notify('CDN 缓存刷新任务已提交','success')}catch(e){var message=safeError(e);$('last-result').textContent='提交失败';await addLog(false,providerName(c.provider)+' · '+label,message);await notify(message,'error')}finally{setBusy(false)}}
async function initPage(){state.isAdmin=await currentAdmin();showAccess(state.isAdmin);if(!state.isAdmin)return;var values=await Promise.all([Tapp.storage.get(CONFIG_KEY),Tapp.storage.get(LOG_KEY)]);state.config=normalizeConfig(values[0]);state.logs=Array.isArray(values[1])?values[1]:[];fillInputs(state.config);renderLogs();$('provider').addEventListener('change',renderProvider);$('save-btn').addEventListener('click',async function(){if(!(await requireAdmin()))return;var c=readInputs(),error=validate(c);if(error)return notify(error,'warning');try{await Tapp.storage.set(CONFIG_KEY,c);state.config=c;$('save-status').textContent='已保存';await notify('CDN 配置已保存','success')}catch(e){$('save-status').textContent='保存失败';await notify('保存配置失败：'+safeError(e),'error')}});$('clear-config-btn').addEventListener('click',async function(){if(!(await requireAdmin()))return;if(!(await Tapp.ui.confirm('确定清除当前保存的 CDN 密钥吗？')))return;state.config=normalizeConfig({provider:$('provider').value});await Tapp.storage.set(CONFIG_KEY,state.config);fillInputs(state.config);$('save-status').textContent='密钥已清除';notify('CDN 密钥已清除','success')});$('add-home-btn').addEventListener('click',function(){var c=readInputs();if(!c.siteUrl)return notify('请先填写站点地址','warning');var urls=parseUrls();if(urls.indexOf(c.siteUrl+'/')<0)urls.unshift(c.siteUrl+'/');$('urls').value=urls.join('\n')});$('dedupe-btn').addEventListener('click',function(){$('urls').value=parseUrls().join('\n')});$('clear-urls-btn').addEventListener('click',function(){$('urls').value=''});$('purge-urls-btn').addEventListener('click',function(){callPurge(parseUrls(),false)});$('purge-all-btn').addEventListener('click',async function(){if(!(await requireAdmin()))return;if(await Tapp.ui.confirm('全站清理会让大量请求回源，确定继续吗？'))callPurge([],true)});$('clear-logs-btn').addEventListener('click',async function(){if(!(await requireAdmin()))return;if(!(await Tapp.ui.confirm('确定清空全部刷新日志吗？')))return;state.logs=[];await saveLogs();renderLogs()})}
(function(){if(window._TAPP_MODE==='page'||window._TAPP_HAS_HTML)Tapp.lifecycle.onReady(initPage)})();